using System.Threading.Tasks;

namespace SlackPublications.SlackApi
{
    /// <summary>
    /// Interface for the Slack Client. Methods generated by hand.
    /// </summary>
    public interface ISlackApi
    {
        /// <summary>
        /// Gets history from a channel.
        /// </summary>
        /// <param name="channel">The Slack channel to get messages from, in the format C1234567890.</param>
        /// <param name="start">The start timestamp.</param>
        /// <param name="end">The end timestamp.</param>
        Task<SlackTypes.ChannelMessages> GetChannelHistory(string channel, int start, int end);

        /// <summary>
        /// Gets a user profile.
        /// </summary>
        /// <param name="user">The Slack user ID, in the format W1234567890.</param>
        Task<SlackTypes.UserInfo> GetUserInfo(string user);
    }
}