using System.Threading.Tasks;
using Refit;

namespace SlackPublicaties.SlackClient
{
    /// <summary>
    /// Interface for the Slack API. Methods generated by hand.
    /// </summary>
    public interface ISlackApi 
    {
        /// <summary>
        /// Gets history from a channel.
        /// </summary>
        /// <param name="token">The Slack OAuth token to use.</param>
        /// <param name="channel">The Slack channel to get messages from, in the format C1234567890.</param>
        /// <param name="start">The start timestamp.</param>
        /// <param name="end">The end timestamp.</param>
        [Get("/channels.history?token={token}&channel={channel}&oldest={start}&latest={end}&count=1000")]
        Task<SlackTypes.ChannelMessages> GetChannelHistory(string token, string channel, int start, int end);

        /// <summary>
        /// Gets a user profile.
        /// </summary>
        /// <param name="token">The Slack OAuth token to use.</param>
        /// <param name="user">The Slack user ID, in the format W1234567890.</param>
        [Get("/users.info?token={token}&user={user}")]
        Task<SlackTypes.UserInfo> GetUserInfo(string token, string user);
    }
}